
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
            
          - name: city
            description: "City"
            tests:
                - not_null

          - name: status
            description: "status"

          - name: code
            description: "city inside a region"
            
          - name: parent_code
            description: "Region"
            
